source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'haml'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.2'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-ui-rails'
gem 'jquery-rails'